/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsernameAuthOptions } from './UsernameAuthOptions';
import {
    UsernameAuthOptionsFromJSON,
    UsernameAuthOptionsFromJSONTyped,
    UsernameAuthOptionsToJSON,
} from './UsernameAuthOptions';
import type { PasswordAuthOptions } from './PasswordAuthOptions';
import {
    PasswordAuthOptionsFromJSON,
    PasswordAuthOptionsFromJSONTyped,
    PasswordAuthOptionsToJSON,
} from './PasswordAuthOptions';

/**
 * 
 * @export
 * @interface AuthOptions
 */
export interface AuthOptions {
    /**
     * 
     * @type {UsernameAuthOptions}
     * @memberof AuthOptions
     */
    username: UsernameAuthOptions;
    /**
     * 
     * @type {PasswordAuthOptions}
     * @memberof AuthOptions
     */
    password: PasswordAuthOptions;
}

/**
 * Check if a given object implements the AuthOptions interface.
 */
export function instanceOfAuthOptions(value: object): value is AuthOptions {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthOptionsFromJSON(json: any): AuthOptions {
    return AuthOptionsFromJSONTyped(json, false);
}

export function AuthOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'username': UsernameAuthOptionsFromJSON(json['username']),
        'password': PasswordAuthOptionsFromJSON(json['password']),
    };
}

export function AuthOptionsToJSON(value?: AuthOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': UsernameAuthOptionsToJSON(value['username']),
        'password': PasswordAuthOptionsToJSON(value['password']),
    };
}

