/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentUserStatus } from './CurrentUserStatus';
import {
    CurrentUserStatusFromJSON,
    CurrentUserStatusFromJSONTyped,
    CurrentUserStatusToJSON,
} from './CurrentUserStatus';
import type { UserPermission } from './UserPermission';
import {
    UserPermissionFromJSON,
    UserPermissionFromJSONTyped,
    UserPermissionToJSON,
} from './UserPermission';

/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.CurrentUser api response data.
 * @export
 * @interface CurrentUserResponseDto
 */
export interface CurrentUserResponseDto {
    /**
     * 
     * @type {CurrentUserStatus}
     * @memberof CurrentUserResponseDto
     */
    status: CurrentUserStatus;
    /**
     * Login username.
     * @type {string}
     * @memberof CurrentUserResponseDto
     */
    userName?: string | null;
    /**
     * Email address.
     * @type {string}
     * @memberof CurrentUserResponseDto
     */
    email?: string | null;
    /**
     * List of roles associated to this user.
     * @type {Set<string>}
     * @memberof CurrentUserResponseDto
     */
    roles?: Set<string> | null;
    /**
     * Permissions related to this user roles.
     * @type {Set<UserPermission>}
     * @memberof CurrentUserResponseDto
     */
    permissions?: Set<UserPermission> | null;
}

/**
 * Check if a given object implements the CurrentUserResponseDto interface.
 */
export function instanceOfCurrentUserResponseDto(value: object): value is CurrentUserResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CurrentUserResponseDtoFromJSON(json: any): CurrentUserResponseDto {
    return CurrentUserResponseDtoFromJSONTyped(json, false);
}

export function CurrentUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': CurrentUserStatusFromJSON(json['status']),
        'userName': json['userName'] == null ? undefined : json['userName'],
        'email': json['email'] == null ? undefined : json['email'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'permissions': json['permissions'] == null ? undefined : (new Set((json['permissions'] as Array<any>).map(UserPermissionFromJSON))),
    };
}

export function CurrentUserResponseDtoToJSON(value?: CurrentUserResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': CurrentUserStatusToJSON(value['status']),
        'userName': value['userName'],
        'email': value['email'],
        'roles': value['roles'] == null ? undefined : Array.from(value['roles'] as Set<any>),
        'permissions': value['permissions'] == null ? undefined : (Array.from(value['permissions'] as Set<any>).map(UserPermissionToJSON)),
    };
}

