/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.CurrentUser response api specific status.
 * 
 * OK (Authentication valid.)
 * 
 * InvalidArgument (Invalid argument.)
 * 
 * InvalidAuthentication (Invalid authentication.)
 * 
 * AccessTokenNotFound (Invalid argument.)
 * @export
 */
export const CurrentUserStatus = {
    OK: 'OK',
    InvalidArgument: 'InvalidArgument',
    InvalidAuthentication: 'InvalidAuthentication',
    AccessTokenNotFound: 'AccessTokenNotFound'
} as const;
export type CurrentUserStatus = typeof CurrentUserStatus[keyof typeof CurrentUserStatus];


export function instanceOfCurrentUserStatus(value: any): boolean {
    for (const key in CurrentUserStatus) {
        if (Object.prototype.hasOwnProperty.call(CurrentUserStatus, key)) {
            if ((CurrentUserStatus as Record<string, CurrentUserStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CurrentUserStatusFromJSON(json: any): CurrentUserStatus {
    return CurrentUserStatusFromJSONTyped(json, false);
}

export function CurrentUserStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUserStatus {
    return json as CurrentUserStatus;
}

export function CurrentUserStatusToJSON(value?: CurrentUserStatus | null): any {
    return value as any;
}

