/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteUserRequestDto
 */
export interface DeleteUserRequestDto {
    /**
     * 
     * @type {string}
     * @memberof DeleteUserRequestDto
     */
    usernameToDelete: string | null;
}

/**
 * Check if a given object implements the DeleteUserRequestDto interface.
 */
export function instanceOfDeleteUserRequestDto(value: object): value is DeleteUserRequestDto {
    if (!('usernameToDelete' in value) || value['usernameToDelete'] === undefined) return false;
    return true;
}

export function DeleteUserRequestDtoFromJSON(json: any): DeleteUserRequestDto {
    return DeleteUserRequestDtoFromJSONTyped(json, false);
}

export function DeleteUserRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUserRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'usernameToDelete': json['usernameToDelete'],
    };
}

export function DeleteUserRequestDtoToJSON(value?: DeleteUserRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'usernameToDelete': value['usernameToDelete'],
    };
}

