/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeleteUserStatus } from './DeleteUserStatus';
import {
    DeleteUserStatusFromJSON,
    DeleteUserStatusFromJSONTyped,
    DeleteUserStatusToJSON,
} from './DeleteUserStatus';

/**
 * 
 * @export
 * @interface DeleteUserResponseDto
 */
export interface DeleteUserResponseDto {
    /**
     * 
     * @type {DeleteUserStatus}
     * @memberof DeleteUserResponseDto
     */
    status: DeleteUserStatus;
    /**
     * List of edit user errors if any.
     * @type {Array<string>}
     * @memberof DeleteUserResponseDto
     */
    errors?: Array<string> | null;
}

/**
 * Check if a given object implements the DeleteUserResponseDto interface.
 */
export function instanceOfDeleteUserResponseDto(value: object): value is DeleteUserResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DeleteUserResponseDtoFromJSON(json: any): DeleteUserResponseDto {
    return DeleteUserResponseDtoFromJSONTyped(json, false);
}

export function DeleteUserResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUserResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': DeleteUserStatusFromJSON(json['status']),
        'errors': json['errors'] == null ? undefined : json['errors'],
    };
}

export function DeleteUserResponseDtoToJSON(value?: DeleteUserResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': DeleteUserStatusToJSON(value['status']),
        'errors': value['errors'],
    };
}

