/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * 
 * OK (Edit user ok.)
 * 
 * IdentityError (asp net core IdentityError, see Errors for details.)
 * 
 * CannotChangeUsername (Username cannot be changed.)
 * 
 * UserNotFound (User not found.)
 * 
 * PermissionsError
 * @export
 */
export const EditUserStatus = {
    OK: 'OK',
    IdentityError: 'IdentityError',
    CannotChangeUsername: 'CannotChangeUsername',
    UserNotFound: 'UserNotFound',
    PermissionsError: 'PermissionsError'
} as const;
export type EditUserStatus = typeof EditUserStatus[keyof typeof EditUserStatus];


export function instanceOfEditUserStatus(value: any): boolean {
    for (const key in EditUserStatus) {
        if (Object.prototype.hasOwnProperty.call(EditUserStatus, key)) {
            if ((EditUserStatus as Record<string, EditUserStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EditUserStatusFromJSON(json: any): EditUserStatus {
    return EditUserStatusFromJSONTyped(json, false);
}

export function EditUserStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditUserStatus {
    return json as EditUserStatus;
}

export function EditUserStatusToJSON(value?: EditUserStatus | null): any {
    return value as any;
}

