/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.LockoutUser(ExampleWebApp.Backend.WebApi.LockoutUserRequestDto) api request data.
 * @export
 * @interface LockoutUserRequestDto
 */
export interface LockoutUserRequestDto {
    /**
     * User name.
     * @type {string}
     * @memberof LockoutUserRequestDto
     */
    userName: string | null;
    /**
     * Lock out end (UTC).
     * @type {Date}
     * @memberof LockoutUserRequestDto
     */
    lockoutEnd: Date;
}

/**
 * Check if a given object implements the LockoutUserRequestDto interface.
 */
export function instanceOfLockoutUserRequestDto(value: object): value is LockoutUserRequestDto {
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('lockoutEnd' in value) || value['lockoutEnd'] === undefined) return false;
    return true;
}

export function LockoutUserRequestDtoFromJSON(json: any): LockoutUserRequestDto {
    return LockoutUserRequestDtoFromJSONTyped(json, false);
}

export function LockoutUserRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LockoutUserRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'lockoutEnd': (new Date(json['lockoutEnd'])),
    };
}

export function LockoutUserRequestDtoToJSON(value?: LockoutUserRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userName': value['userName'],
        'lockoutEnd': ((value['lockoutEnd']).toISOString()),
    };
}

