/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.Login(ExampleWebApp.Backend.WebApi.LoginRequestDto) response api specific status.
 * 
 * OK (Login vaild.)
 * 
 * UsernameOrEmailRequired (Missing username or email.)
 * 
 * InvalidAuthentication (Invalid authentication.)
 * 
 * InvalidHttpContext (Authentication http context.)
 * @export
 */
export const LoginStatus = {
    OK: 'OK',
    UsernameOrEmailRequired: 'UsernameOrEmailRequired',
    InvalidAuthentication: 'InvalidAuthentication',
    InvalidHttpContext: 'InvalidHttpContext'
} as const;
export type LoginStatus = typeof LoginStatus[keyof typeof LoginStatus];


export function instanceOfLoginStatus(value: any): boolean {
    for (const key in LoginStatus) {
        if (Object.prototype.hasOwnProperty.call(LoginStatus, key)) {
            if ((LoginStatus as Record<string, LoginStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LoginStatusFromJSON(json: any): LoginStatus {
    return LoginStatusFromJSONTyped(json, false);
}

export function LoginStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginStatus {
    return json as LoginStatus;
}

export function LoginStatusToJSON(value?: LoginStatus | null): any {
    return value as any;
}

