/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.RegisterUser(ExampleWebApp.Backend.WebApi.RegisterUserRequestDto) api request data.
 * @export
 * @interface RegisterUserRequestDto
 */
export interface RegisterUserRequestDto {
    /**
     * User name.
     * @type {string}
     * @memberof RegisterUserRequestDto
     */
    userName: string | null;
    /**
     * User email.
     * @type {string}
     * @memberof RegisterUserRequestDto
     */
    email: string | null;
    /**
     * User password.
     * @type {string}
     * @memberof RegisterUserRequestDto
     */
    password: string | null;
}

/**
 * Check if a given object implements the RegisterUserRequestDto interface.
 */
export function instanceOfRegisterUserRequestDto(value: object): value is RegisterUserRequestDto {
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegisterUserRequestDtoFromJSON(json: any): RegisterUserRequestDto {
    return RegisterUserRequestDtoFromJSONTyped(json, false);
}

export function RegisterUserRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function RegisterUserRequestDtoToJSON(value?: RegisterUserRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userName': value['userName'],
        'email': value['email'],
        'password': value['password'],
    };
}

