/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.RegisterUser(ExampleWebApp.Backend.WebApi.RegisterUserRequestDto) response api specific status.
 * 
 * OK (Registration ok.)
 * 
 * IdentityError (Identity error.)
 * @export
 */
export const RegisterUserStatus = {
    OK: 'OK',
    IdentityError: 'IdentityError'
} as const;
export type RegisterUserStatus = typeof RegisterUserStatus[keyof typeof RegisterUserStatus];


export function instanceOfRegisterUserStatus(value: any): boolean {
    for (const key in RegisterUserStatus) {
        if (Object.prototype.hasOwnProperty.call(RegisterUserStatus, key)) {
            if ((RegisterUserStatus as Record<string, RegisterUserStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RegisterUserStatusFromJSON(json: any): RegisterUserStatus {
    return RegisterUserStatusFromJSONTyped(json, false);
}

export function RegisterUserStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterUserStatus {
    return json as RegisterUserStatus;
}

export function RegisterUserStatusToJSON(value?: RegisterUserStatus | null): any {
    return value as any;
}

