/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetUserRolesStatus } from './SetUserRolesStatus';
import {
    SetUserRolesStatusFromJSON,
    SetUserRolesStatusFromJSONTyped,
    SetUserRolesStatusToJSON,
} from './SetUserRolesStatus';

/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.SetUserRoles(ExampleWebApp.Backend.WebApi.SetUserRolesRequestDto) api response data.
 * @export
 * @interface SetUserRolesResponseDto
 */
export interface SetUserRolesResponseDto {
    /**
     * 
     * @type {SetUserRolesStatus}
     * @memberof SetUserRolesResponseDto
     */
    status: SetUserRolesStatus;
    /**
     * Roles added.
     * @type {Array<string>}
     * @memberof SetUserRolesResponseDto
     */
    rolesAdded?: Array<string> | null;
    /**
     * Roles removed.
     * @type {Array<string>}
     * @memberof SetUserRolesResponseDto
     */
    rolesRemoved?: Array<string> | null;
}

/**
 * Check if a given object implements the SetUserRolesResponseDto interface.
 */
export function instanceOfSetUserRolesResponseDto(value: object): value is SetUserRolesResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SetUserRolesResponseDtoFromJSON(json: any): SetUserRolesResponseDto {
    return SetUserRolesResponseDtoFromJSONTyped(json, false);
}

export function SetUserRolesResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserRolesResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': SetUserRolesStatusFromJSON(json['status']),
        'rolesAdded': json['rolesAdded'] == null ? undefined : json['rolesAdded'],
        'rolesRemoved': json['rolesRemoved'] == null ? undefined : json['rolesRemoved'],
    };
}

export function SetUserRolesResponseDtoToJSON(value?: SetUserRolesResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': SetUserRolesStatusToJSON(value['status']),
        'rolesAdded': value['rolesAdded'],
        'rolesRemoved': value['rolesRemoved'],
    };
}

