/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.SetUserRoles(ExampleWebApp.Backend.WebApi.SetUserRolesRequestDto) response api specific status.
 * 
 * OK (Set user roles successful.)
 * 
 * InternalError (Internal error.)
 * 
 * AdminRolesReadOnly (Can't change admin role.)
 * 
 * UserNotFound (User not found.)
 * @export
 */
export const SetUserRolesStatus = {
    OK: 'OK',
    InternalError: 'InternalError',
    AdminRolesReadOnly: 'AdminRolesReadOnly',
    UserNotFound: 'UserNotFound'
} as const;
export type SetUserRolesStatus = typeof SetUserRolesStatus[keyof typeof SetUserRolesStatus];


export function instanceOfSetUserRolesStatus(value: any): boolean {
    for (const key in SetUserRolesStatus) {
        if (Object.prototype.hasOwnProperty.call(SetUserRolesStatus, key)) {
            if ((SetUserRolesStatus as Record<string, SetUserRolesStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SetUserRolesStatusFromJSON(json: any): SetUserRolesStatus {
    return SetUserRolesStatusFromJSONTyped(json, false);
}

export function SetUserRolesStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserRolesStatus {
    return json as SetUserRolesStatus;
}

export function SetUserRolesStatusToJSON(value?: SetUserRolesStatus | null): any {
    return value as any;
}

