/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.SetUserRoles(ExampleWebApp.Backend.WebApi.SetUserRolesRequestDto) api request data.
 * @export
 * @interface SetUserRolesRequestDto
 */
export interface SetUserRolesRequestDto {
    /**
     * User name.
     * @type {string}
     * @memberof SetUserRolesRequestDto
     */
    userName: string | null;
    /**
     * Roles to set to the user.
     * @type {Array<string>}
     * @memberof SetUserRolesRequestDto
     */
    roles: Array<string> | null;
}

/**
 * Check if a given object implements the SetUserRolesRequestDto interface.
 */
export function instanceOfSetUserRolesRequestDto(value: object): value is SetUserRolesRequestDto {
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    return true;
}

export function SetUserRolesRequestDtoFromJSON(json: any): SetUserRolesRequestDto {
    return SetUserRolesRequestDtoFromJSONTyped(json, false);
}

export function SetUserRolesRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetUserRolesRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'roles': json['roles'],
    };
}

export function SetUserRolesRequestDtoToJSON(value?: SetUserRolesRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userName': value['userName'],
        'roles': value['roles'],
    };
}

