/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsernameAuthOptions
 */
export interface UsernameAuthOptions {
    /**
     * 
     * @type {string}
     * @memberof UsernameAuthOptions
     */
    allowedUserNameCharacters: string | null;
}

/**
 * Check if a given object implements the UsernameAuthOptions interface.
 */
export function instanceOfUsernameAuthOptions(value: object): value is UsernameAuthOptions {
    if (!('allowedUserNameCharacters' in value) || value['allowedUserNameCharacters'] === undefined) return false;
    return true;
}

export function UsernameAuthOptionsFromJSON(json: any): UsernameAuthOptions {
    return UsernameAuthOptionsFromJSONTyped(json, false);
}

export function UsernameAuthOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsernameAuthOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedUserNameCharacters': json['allowedUserNameCharacters'],
    };
}

export function UsernameAuthOptionsToJSON(value?: UsernameAuthOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'allowedUserNameCharacters': value['allowedUserNameCharacters'],
    };
}

