/* tslint:disable */
/* eslint-disable */
/**
 * ExampleWebApp API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthOptions,
  CurrentUserResponseDto,
  DeleteUserRequestDto,
  DeleteUserResponseDto,
  EditUserRequestDto,
  EditUserResponseDto,
  LoginRequestDto,
  LoginResponseDto,
  UserListItemResponseDto,
} from '../models/index';
import {
    AuthOptionsFromJSON,
    AuthOptionsToJSON,
    CurrentUserResponseDtoFromJSON,
    CurrentUserResponseDtoToJSON,
    DeleteUserRequestDtoFromJSON,
    DeleteUserRequestDtoToJSON,
    DeleteUserResponseDtoFromJSON,
    DeleteUserResponseDtoToJSON,
    EditUserRequestDtoFromJSON,
    EditUserRequestDtoToJSON,
    EditUserResponseDtoFromJSON,
    EditUserResponseDtoToJSON,
    LoginRequestDtoFromJSON,
    LoginRequestDtoToJSON,
    LoginResponseDtoFromJSON,
    LoginResponseDtoToJSON,
    UserListItemResponseDtoFromJSON,
    UserListItemResponseDtoToJSON,
} from '../models/index';

export interface ApiAuthDeleteUserPostRequest {
    deleteUserRequestDto?: DeleteUserRequestDto;
}

export interface ApiAuthEditUserPostRequest {
    editUserRequestDto?: EditUserRequestDto;
}

export interface ApiAuthListUsersGetRequest {
    username?: string;
}

export interface ApiAuthLoginPostRequest {
    loginRequestDto?: LoginRequestDto;
}

export interface ApiAuthResetLostPasswordGetRequest {
    email?: string;
    token?: string;
    resetPassword?: string;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Retrieve auth options.
     */
    async apiAuthAuthOptionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthOptions>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Auth/AuthOptions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthOptionsFromJSON(jsonValue));
    }

    /**
     * Retrieve auth options.
     */
    async apiAuthAuthOptionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthOptions> {
        const response = await this.apiAuthAuthOptionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve current logged in user name, email, roles.
     */
    async apiAuthCurrentUserGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurrentUserResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Auth/CurrentUser`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurrentUserResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieve current logged in user name, email, roles.
     */
    async apiAuthCurrentUserGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurrentUserResponseDto> {
        const response = await this.apiAuthCurrentUserGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete user.
     */
    async apiAuthDeleteUserPostRaw(requestParameters: ApiAuthDeleteUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteUserResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Auth/DeleteUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteUserRequestDtoToJSON(requestParameters['deleteUserRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteUserResponseDtoFromJSON(jsonValue));
    }

    /**
     * Delete user.
     */
    async apiAuthDeleteUserPost(requestParameters: ApiAuthDeleteUserPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteUserResponseDto> {
        const response = await this.apiAuthDeleteUserPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Edit user data
     */
    async apiAuthEditUserPostRaw(requestParameters: ApiAuthEditUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EditUserResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Auth/EditUser`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EditUserRequestDtoToJSON(requestParameters['editUserRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EditUserResponseDtoFromJSON(jsonValue));
    }

    /**
     * Edit user data
     */
    async apiAuthEditUserPost(requestParameters: ApiAuthEditUserPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EditUserResponseDto> {
        const response = await this.apiAuthEditUserPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all roles.
     */
    async apiAuthListRolesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Auth/ListRoles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List all roles.
     */
    async apiAuthListRolesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiAuthListRolesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * List all users or specific if param given.
     */
    async apiAuthListUsersGetRaw(requestParameters: ApiAuthListUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserListItemResponseDto>>> {
        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Auth/ListUsers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserListItemResponseDtoFromJSON));
    }

    /**
     * List all users or specific if param given.
     */
    async apiAuthListUsersGet(requestParameters: ApiAuthListUsersGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserListItemResponseDto>> {
        const response = await this.apiAuthListUsersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Login user by given username or email and auth password.
     */
    async apiAuthLoginPostRaw(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/Auth/Login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestDtoToJSON(requestParameters['loginRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseDtoFromJSON(jsonValue));
    }

    /**
     * Login user by given username or email and auth password.
     */
    async apiAuthLoginPost(requestParameters: ApiAuthLoginPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResponseDto> {
        const response = await this.apiAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Logout current user.
     */
    async apiAuthLogoutGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Auth/Logout`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Logout current user.
     */
    async apiAuthLogoutGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthLogoutGetRaw(initOverrides);
    }

    /**
     * Reset lost password.
     */
    async apiAuthResetLostPasswordGetRaw(requestParameters: ApiAuthResetLostPasswordGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        if (requestParameters['resetPassword'] != null) {
            queryParameters['resetPassword'] = requestParameters['resetPassword'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Auth/ResetLostPassword`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reset lost password.
     */
    async apiAuthResetLostPasswordGet(requestParameters: ApiAuthResetLostPasswordGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAuthResetLostPasswordGetRaw(requestParameters, initOverrides);
    }

}
