/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *   Ping  Pong
 */
export const AliveWSMessageType = {

    /**
     * 
     */
    Ping: 'Ping',

    /**
     * 
     */
    Pong: 'Pong'
} as const;
export type AliveWSMessageType = typeof AliveWSMessageType[keyof typeof AliveWSMessageType];

