/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsernameAuthOptions } from './usernameAuthOptions';
import { PasswordAuthOptions } from './passwordAuthOptions';


export interface AuthOptions { 
    username: UsernameAuthOptions;
    password: PasswordAuthOptions;
}

