/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *   Custom  Ping  Pong
 */
export const BaseWSProtocolType = {

    /**
     * 
     */
    Custom: 'Custom',

    /**
     * 
     */
    Ping: 'Ping',

    /**
     * 
     */
    Pong: 'Pong'
} as const;
export type BaseWSProtocolType = typeof BaseWSProtocolType[keyof typeof BaseWSProtocolType];

