/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.CurrentUser response api specific status.  OK (Authentication valid.)  InvalidAuthentication (Invalid authentication.)  InvalidArgument (Invalid argument.)  AccessTokenNotFound (Access token not found.)
 */
export const CurrentUserStatus = {

    /**
     * Authentication valid.
     */
    OK: 'OK',

    /**
     * Invalid authentication.
     */
    InvalidAuthentication: 'InvalidAuthentication',

    /**
     * Invalid argument.
     */
    InvalidArgument: 'InvalidArgument',

    /**
     * Access token not found.
     */
    AccessTokenNotFound: 'AccessTokenNotFound'
} as const;
export type CurrentUserStatus = typeof CurrentUserStatus[keyof typeof CurrentUserStatus];

