/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *   OK (Delete user ok.)  IdentityError (asp net core IdentityError, see Errors for details.)  UserNotFound (User not found.)  CannotDeleteLastActiveAdmin (Cannot delete last non disabled admin user.)  PermissionsError
 */
export const DeleteUserStatus = {

    /**
     * Delete user ok.
     */
    OK: 'OK',

    /**
     * asp net core IdentityError, see Errors for details.
     */
    IdentityError: 'IdentityError',

    /**
     * User not found.
     */
    UserNotFound: 'UserNotFound',

    /**
     * Cannot delete last non disabled admin user.
     */
    CannotDeleteLastActiveAdmin: 'CannotDeleteLastActiveAdmin',

    /**
     * 
     */
    PermissionsError: 'PermissionsError'
} as const;
export type DeleteUserStatus = typeof DeleteUserStatus[keyof typeof DeleteUserStatus];

