/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeleteUserStatus } from './deleteUserStatus';


export interface DeleteUserResponseDto { 
    status: DeleteUserStatus;
    /**
     * List of edit user errors if any.
     */
    errors?: Array<string> | null;
}
export namespace DeleteUserResponseDto {
}


