/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Edit user data
 */
export interface EditUserRequestDto { 
    /**
     * Existing User name or null to create a new one using ExampleWebApp.Backend.WebApi.Services.Abstractions.Auth.DTOs.EditUserRequestDto.EditUsername.
     */
    existingUsername?: string | null;
    /**
     * New email or null to leave unchanged.
     */
    editEmail?: string | null;
    /**
     * New username or null to leave unchanged.
     */
    editUsername?: string | null;
    /**
     * New password or null to leave unchanged.
     */
    editPassword?: string | null;
    /**
     * Roles to set to the user or null to leave unchanged.
     */
    editRoles?: Array<string> | null;
    /**
     * If true the user can\'t login after previous release access token expires.
     */
    editDisabled?: boolean | null;
    /**
     * Set the end date of lockout.  The user will be unable to login until ExampleWebApp.Backend.WebApi.Services.Abstractions.Auth.DTOs.EditUserRequestDto.EditLockoutEnd.  If ExampleWebApp.Backend.WebApi.Services.Abstractions.Auth.DTOs.EditUserRequestDto.EditLockoutEnd is set in the past the user will be re-enabled immediately.
     */
    editLockoutEnd?: string | null;
}

