/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *   OK (Edit user ok.)  IdentityError (asp net core IdentityError, see Errors for details.)  CannotChangeUsername (Username cannot be changed.)  UserNotFound (User not found.)  PermissionsError
 */
export const EditUserStatus = {

    /**
     * Edit user ok.
     */
    OK: 'OK',

    /**
     * asp net core IdentityError, see Errors for details.
     */
    IdentityError: 'IdentityError',

    /**
     * Username cannot be changed.
     */
    CannotChangeUsername: 'CannotChangeUsername',

    /**
     * User not found.
     */
    UserNotFound: 'UserNotFound',

    /**
     * 
     */
    PermissionsError: 'PermissionsError'
} as const;
export type EditUserStatus = typeof EditUserStatus[keyof typeof EditUserStatus];

