/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EditUserStatus } from './editUserStatus';


export interface EditUserResponseDto { 
    status: EditUserStatus;
    /**
     * Roles added.
     */
    rolesAdded?: Array<string> | null;
    /**
     * Roles removed.
     */
    rolesRemoved?: Array<string> | null;
    /**
     * List of edit user errors if any.
     */
    errors?: Array<string> | null;
}
export namespace EditUserResponseDto {
}


