/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *   MyProto1  MyProto2  SrvMem
 */
export const ExampleWSProtocolType = {

    /**
     * 
     */
    MyProto1: 'MyProto1',

    /**
     * 
     */
    MyProto2: 'MyProto2',

    /**
     * 
     */
    SrvMem: 'SrvMem'
} as const;
export type ExampleWSProtocolType = typeof ExampleWSProtocolType[keyof typeof ExampleWSProtocolType];

