/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FakeData } from './fakeData';


export interface FakeDataGenericItemWithOrig { 
    origItem?: FakeData;
    updatedItem: FakeData;
}

