/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenericSort } from './genericSort';


/**
 * get request
 */
export interface GetGenericRequest { 
    /**
     * paged from
     */
    offset?: number;
    /**
     * paged size (-1 disabled)
     */
    count?: number;
    /**
     * ef core dynamic filter
     */
    dynFilter?: string | null;
    sort?: GenericSort;
}

