/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.Login(ExampleWebApp.Backend.WebApi.Services.Abstractions.Auth.DTOs.LoginRequestDto) api request data.
 */
export interface LoginRequestDto { 
    /**
     * Username or email.
     */
    usernameOrEmail?: string | null;
    /**
     * Password.
     */
    password: string;
    passwordResetToken?: string | null;
}

