/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.Login(ExampleWebApp.Backend.WebApi.Services.Auth.DTOs.LoginRequestDto) response api specific status.  OK (Login vaild.)  UsernameOrEmailRequired (Missing username or email.)  InvalidAuthentication (Invalid authentication.)  InvalidHttpContext (Authentication http context.)
 */
export const LoginStatus = {

    /**
     * Login vaild.
     */
    OK: 'OK',

    /**
     * Missing username or email.
     */
    UsernameOrEmailRequired: 'UsernameOrEmailRequired',

    /**
     * Invalid authentication.
     */
    InvalidAuthentication: 'InvalidAuthentication',

    /**
     * Authentication http context.
     */
    InvalidHttpContext: 'InvalidHttpContext'
} as const;
export type LoginStatus = typeof LoginStatus[keyof typeof LoginStatus];

