/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoginStatus } from './loginStatus';
import { UserPermission } from './userPermission';


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.Login(ExampleWebApp.Backend.WebApi.Services.Auth.DTOs.LoginRequestDto) api response data.
 */
export interface LoginResponseDto { 
    status: LoginStatus;
    /**
     * Username.
     */
    userName?: string | null;
    /**
     * Email.
     */
    email?: string | null;
    /**
     * User roles.
     */
    roles?: Array<string> | null;
    errors?: Array<string> | null;
    /**
     * Permissions related to this user roles.
     */
    permissions?: Set<UserPermission> | null;
    /**
     * Expiration timestamp for the refresh token. To keep alive auth issue M:ExampleWebApp.Backend.WebApi.AuthController.RenewRefreshToken before  token expire.
     */
    refreshTokenExpiration?: string;
}
export namespace LoginResponseDto {
}


