/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.RenewRefreshToken response api specific status.  OK (Authentication valid.)  InvalidAuthentication (Invalid authentication.)  InvalidHttpContext (Invalid http context.)  AccessTokenNotFound (Access token not found.)  InvalidRefreshToken (Invalid refresh token.)
 */
export const RenewRefreshTokenStatus = {

    /**
     * Authentication valid.
     */
    OK: 'OK',

    /**
     * Invalid authentication.
     */
    InvalidAuthentication: 'InvalidAuthentication',

    /**
     * Invalid http context.
     */
    InvalidHttpContext: 'InvalidHttpContext',

    /**
     * Access token not found.
     */
    AccessTokenNotFound: 'AccessTokenNotFound',

    /**
     * Invalid refresh token.
     */
    InvalidRefreshToken: 'InvalidRefreshToken'
} as const;
export type RenewRefreshTokenStatus = typeof RenewRefreshTokenStatus[keyof typeof RenewRefreshTokenStatus];

