/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.RenewAccessToken response api specific status.  OK (Valid refresh token, thus access token renewd.)  InvalidAuthentication (Invalid authentication.)  InvalidAccessToken (Invalid access token.)  InvalidRefreshToken (Invalid refresh token.)  InvalidHttpContext (Invalid http context.)
 */
export const RenewAccessTokenStatus = {

    /**
     * Valid refresh token, thus access token renewd.
     */
    OK: 'OK',

    /**
     * Invalid authentication.
     */
    InvalidAuthentication: 'InvalidAuthentication',

    /**
     * Invalid access token.
     */
    InvalidAccessToken: 'InvalidAccessToken',

    /**
     * Invalid refresh token.
     */
    InvalidRefreshToken: 'InvalidRefreshToken',

    /**
     * Invalid http context.
     */
    InvalidHttpContext: 'InvalidHttpContext'
} as const;
export type RenewAccessTokenStatus = typeof RenewAccessTokenStatus[keyof typeof RenewAccessTokenStatus];

