/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RefreshTokenNfo } from './refreshTokenNfo';
import { RenewRefreshTokenStatus } from './renewRefreshTokenStatus';


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.RenewRefreshToken api response data.
 */
export interface RenewRefreshTokenResponse { 
    status: RenewRefreshTokenStatus;
    refreshTokenNfo?: RefreshTokenNfo;
}
export namespace RenewRefreshTokenResponse {
}


