/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessTokenNfo } from './accessTokenNfo';
import { RenewAccessTokenStatus } from './renewAccessTokenStatus';


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.RenewAccessToken api response data.
 */
export interface RenewAccessTokenResponse { 
    status: RenewAccessTokenStatus;
    accessTokenNfo?: AccessTokenNfo;
}
export namespace RenewAccessTokenResponse {
}


