/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *   ChangeUserRoles (Change another user roles.)  CreateAdminUser (Can create another user with \"admin\" role.)  CreateAdvancedUser (Can create another user with \"advanced\" role.)  CreateNormalUser (Can create another user with \"normal\" role.)  ChangeOwnEmail (Change its own email (without need to validate).)  ChangeOwnPassword (Change its own password (by reset).)  ChangeNormalUserEmail (Change email of another user which max role is \"normal\".)  ChangeAdvancedUserEmail (Change email of another user which max role is \"advanced\".)  ChangeAdminUserEmail (Change email of another user which max role is \"admin\".)  ResetNormalUserPassword (Reset password of another user which max role is \"normal\".)  ResetAdvancedUserPassword (Reset password of another user which max role is \"advanced\".)  ResetAdminUserPassword (Reset password of another user which max role is \"normal\".)  LockoutAdminUser (Edit lockout of another user which max role is \"admin\".)  LockoutAdvancedUser (Edit lockout of another user which max role is \"advanced\".)  LockoutNormalUser (Edit lockout of another user which max role is \"normal\".)  DeleteAdminUser (Delete user which max role is \"admin\".)  DeleteAdvancedUser (Delete user which max role is \"advanced\".)  DeleteNormalUser (Delete user which max role is \"normal\".)  DisableAdminUser (Disable user which max role is \"admin\".)  DisableAdvancedUser (Disable user which max role is \"advanced\".)  DisableNormalUser (Disable user which max role is \"normal\".)  ResetLostPassword (Generate an email with a reset password token.)
 */
export const UserPermission = {

    /**
     * Change another user roles.
     */
    ChangeUserRoles: 'ChangeUserRoles',

    /**
     * Can create another user with &quot;admin&quot; role.
     */
    CreateAdminUser: 'CreateAdminUser',

    /**
     * Can create another user with &quot;advanced&quot; role.
     */
    CreateAdvancedUser: 'CreateAdvancedUser',

    /**
     * Can create another user with &quot;normal&quot; role.
     */
    CreateNormalUser: 'CreateNormalUser',

    /**
     * Change its own email (without need to validate).
     */
    ChangeOwnEmail: 'ChangeOwnEmail',

    /**
     * Change its own password (by reset).
     */
    ChangeOwnPassword: 'ChangeOwnPassword',

    /**
     * Change email of another user which max role is &quot;normal&quot;.
     */
    ChangeNormalUserEmail: 'ChangeNormalUserEmail',

    /**
     * Change email of another user which max role is &quot;advanced&quot;.
     */
    ChangeAdvancedUserEmail: 'ChangeAdvancedUserEmail',

    /**
     * Change email of another user which max role is &quot;admin&quot;.
     */
    ChangeAdminUserEmail: 'ChangeAdminUserEmail',

    /**
     * Reset password of another user which max role is &quot;normal&quot;.
     */
    ResetNormalUserPassword: 'ResetNormalUserPassword',

    /**
     * Reset password of another user which max role is &quot;advanced&quot;.
     */
    ResetAdvancedUserPassword: 'ResetAdvancedUserPassword',

    /**
     * Reset password of another user which max role is &quot;normal&quot;.
     */
    ResetAdminUserPassword: 'ResetAdminUserPassword',

    /**
     * Edit lockout of another user which max role is &quot;admin&quot;.
     */
    LockoutAdminUser: 'LockoutAdminUser',

    /**
     * Edit lockout of another user which max role is &quot;advanced&quot;.
     */
    LockoutAdvancedUser: 'LockoutAdvancedUser',

    /**
     * Edit lockout of another user which max role is &quot;normal&quot;.
     */
    LockoutNormalUser: 'LockoutNormalUser',

    /**
     * Delete user which max role is &quot;admin&quot;.
     */
    DeleteAdminUser: 'DeleteAdminUser',

    /**
     * Delete user which max role is &quot;advanced&quot;.
     */
    DeleteAdvancedUser: 'DeleteAdvancedUser',

    /**
     * Delete user which max role is &quot;normal&quot;.
     */
    DeleteNormalUser: 'DeleteNormalUser',

    /**
     * Disable user which max role is &quot;admin&quot;.
     */
    DisableAdminUser: 'DisableAdminUser',

    /**
     * Disable user which max role is &quot;advanced&quot;.
     */
    DisableAdvancedUser: 'DisableAdvancedUser',

    /**
     * Disable user which max role is &quot;normal&quot;.
     */
    DisableNormalUser: 'DisableNormalUser',

    /**
     * Generate an email with a reset password token.
     */
    ResetLostPassword: 'ResetLostPassword'
} as const;
export type UserPermission = typeof UserPermission[keyof typeof UserPermission];

