/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * M:ExampleWebApp.Backend.WebApi.AuthController.ListUsers(System.String) api response data.
 */
export interface UserListItemResponseDto { 
    /**
     * User name.
     */
    userName: string;
    /**
     * User email.
     */
    email: string;
    /**
     * User roles.
     */
    roles: Array<string>;
    disabled: boolean;
    /**
     * Access failed count.
     */
    accessFailedCount: number;
    /**
     * Email is confirmed.
     */
    emailConfirmed: boolean;
    /**
     * Lockout end (UTC). ExampleWebApp.Backend.WebApi.Services.Auth.DTOs.UserListItemResponseDto.LockoutEnabled.
     */
    lockoutEnd?: string | null;
    /**
     * If true the user is lockout until ExampleWebApp.Backend.WebApi.Services.Auth.DTOs.UserListItemResponseDto.LockoutEnd.
     */
    lockoutEnabled: boolean;
    /**
     * User phone number.
     */
    phoneNumber?: string | null;
    /**
     * User phone number confirmed.
     */
    phoneNumberConfirmed: boolean;
    /**
     * Two factor enabled.
     */
    twoFactorEnabled: boolean;
}

