/**
 * ExampleWebApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AliveWSMessageType } from './aliveWSMessageType';


export interface WSPing { 
    messageType?: AliveWSMessageType;
    msg?: string | null;
}
export namespace WSPing {
}


